# Site settings
title: dnbailey
email: artist@dnbailey.org
description: > # this means to ignore newlines until "baseurl:"
  I am a teacher, an artist, and a human. Exploring the world visually means I have many interests. Hopefully the things I create can inspire you.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dnbailey.org" # the base hostname & protocol for your site
twitter_username: dnbailey
github_username:  dnbailey

# Build settings
markdown: kramdown
